..............................................................................................................................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 446 tests in 0.787s

OK
EE
======================================================================
ERROR: server_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: server_tests
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/solbrig/git/hsolbrig/fhir_model_generator/tests/server_tests.py", line 8, in <module>
    import server
  File "/Users/solbrig/git/hsolbrig/fhir_model_generator/tests/server.py", line 12, in <module>
    from auth import FHIRAuth
ModuleNotFoundError: No module named 'auth'


======================================================================
ERROR: fhirreference_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: fhirreference_tests
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'fhirreference_tests'


----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (errors=2)
